### ISSUE TITLE
loss don't convergence

### ISSUE THREAD

**Issue by hyx100e** [iamyuanchung/Autoregressive-Predictive-Coding#1]
I trained APC by myself data process , but it seem don't convergence in train. and your dataset is too slow to download . I want to know what's the value of loss when you stop your training ?thanks

**Comment by iamyuanchung** [comment]
I tested the download myself and it is working fine. Maybe you can try axel with more connections (e.g., setting -n 10)?

===
The loss depends on the time step n you pick, below is the train loss for different n after 100 epochs (on librispeech train-clean-360):
n = 1: 0.53
n = 2: 0.73
n = 3: 0.87
n = 5: 1.09
n = 10: 1.38
n = 20: 1.59
