### ISSUE TITLE
Will TransformerAPC and ASR test code be released?

### ISSUE THREAD

**Issue by xinedison** [iamyuanchung/Autoregressive-Predictive-Coding#2]
Hi, Yu-An Chung,
    Thank you for releasing your work on APC. I am doing reseach on topic music information retrieval and think your work may helpful for us.
    I found that Transformer-APC is not included in current code version. So as to the test part for the ASR test experiment in paper  GENERATIVE PRE-TRAINING FOR SPEECH WITH AUTOREGRESSIVE PREDICTIVE CODING. 
    I wonder whether you will have plan to release them out in the future? Hope to get your reply.

**Comment by iamyuanchung** [comment]
The Transformer code will be added to this repository soon. I am now doing some local testing to make the batching more efficient.

As for the ASR experiments, I am mainly using the seq2seq model from https://github.com/awni/speech with very few changes. So far I'm not planning to release this part.

**Comment by xinedison** [comment]
@iamyuanchung Thanks for your help and reply.
