### ISSUE TITLE
Replace kaldi feature with torchaudio fbank feature?

### ISSUE THREAD

**Issue by toco2270853** [iamyuanchung/Autoregressive-Predictive-Coding#5]
Hello, I'm currently trying APC, but I'm not familiar with kaldi, and I found that torchaudio provide fbank function that match Kaldi’s compute-fbank-feat. I'm wondering is it possible to use fbank for creating the same feature?If so, how can I set the parameter?
![image](https://user-images.githubusercontent.com/18654148/90975136-44ae8600-e564-11ea-8600-2d3441bbc61e.png)

**Comment by iamyuanchung** [comment]
You can check the conf we used to extract features with kaldi in #4.

**Comment by toco2270853** [comment]
get it, thanks!
