### ISSUE TITLE
`blogmel` files are not available

### ISSUE THREAD

**Issue by simon-rtzr** [iamyuanchung/Autoregressive-Predictive-Coding#6]
Hi,
There's a problem with the feature files.

After downloading the `train-clean-360.xz` and `dev-clean.xz`via dropbox link on the README.md,
I've tried to unzip them

But `xz -d` just produced `train-clean-360` (no file extensions), which is not readable with numpy or pickle.

Can I get the feature files?

Thank you :)

**Comment by iamyuanchung** [comment]
Thanks for raising this issue.

Did you download the data with wget? I suspect there's issue with using wget for Dropbox/GoogleDrive links. Can you try downloading the data directly from Dropbox and see if the file extension exists?

**Comment by simon-rtzr** [comment]
I've downloaded them directly from dropbox via chrome browser.
And their original extensions were `.xz`.

**Comment by iamyuanchung** [comment]
Can you then unzip data with xz -d?

**Comment by simon-rtzr** [comment]
Yes,
I've tried to unzip them from Linux and MacOS with `xz -d`,
and `xz` didn't produce any error massages.

However, unzipped files had no extensions,
and were not loadable with python(numpy or pickle) in both Linux/MacOS cases.

I will google this issue to find whether it is related to `xz` or my environment.

**Comment by iamyuanchung** [comment]
You can add the extension .blogmel yourself.
