### ISSUE TITLE
Could you please share the preprocessing parameters such as window and hop lengths?

### ISSUE THREAD

**Issue by Aria-K-Alethia** [iamyuanchung/Autoregressive-Predictive-Coding#8]
Hi,
Thank you for sharing your code. Great work !
Since I think preprocessing parameters like hop length and window length are important for APC. Also I want to do experiments on other dataset. 
So could you please share them, or share a preprocessing script ?

**Comment by iamyuanchung** [comment]
Please check the conf we used to extract features with kaldi in #4. Thanks.
